import { useState, useEffect } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { User, Mail, AlertCircle } from "lucide-react";
import { useProfile } from "@/hooks/useProfile";

interface ProfileDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  userId?: string;
}

export function ProfileDialog({ open, onOpenChange, userId }: ProfileDialogProps) {
  const { profile, updateDisplayName } = useProfile(userId);
  const [newName, setNewName] = useState('');
  const [savingName, setSavingName] = useState(false);

  useEffect(() => {
    if (open && profile?.display_name) {
      setNewName(profile.display_name);
    }
  }, [open, profile?.display_name]);

  const handleSaveName = async () => {
    if (!newName.trim()) return;
    setSavingName(true);
    await updateDisplayName(newName);
    setSavingName(false);
    onOpenChange(false);
  };

  // Check if the display name looks like an email prefix (auto-generated)
  const isAutoGeneratedName = profile?.display_name && profile.email && 
    profile.display_name.toLowerCase() === profile.email.split('@')[0].toLowerCase();

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md max-w-[calc(100vw-20px)]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-lg font-bold">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary/10">
              <User className="h-5 w-5 text-primary" />
            </div>
            Your Profile
          </DialogTitle>
          <DialogDescription className="text-base">
            Manage your profile information
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-5 pt-4">
          {/* Email Display */}
          {profile?.email && (
            <div className="space-y-2">
              <Label className="text-sm font-medium text-muted-foreground flex items-center gap-2">
                <Mail className="h-4 w-4" />
                Email
              </Label>
              <div className="h-11 flex items-center px-3 rounded-md border bg-muted/30 text-base text-foreground">
                {profile.email}
              </div>
            </div>
          )}

          {/* Auto-generated name warning */}
          {isAutoGeneratedName && (
            <div className="flex items-start gap-3 p-3 rounded-lg bg-amber-500/10 border border-amber-500/20">
              <AlertCircle className="h-5 w-5 text-amber-500 shrink-0 mt-0.5" />
              <div className="text-sm">
                <p className="font-medium text-amber-600 dark:text-amber-400">Display name not set</p>
                <p className="text-muted-foreground mt-1">
                  Your name was automatically set from your email. Update it to show your real name to other trip members.
                </p>
              </div>
            </div>
          )}

          {/* Display Name Input */}
          <div className="space-y-2">
            <Label htmlFor="displayName" className="text-base font-semibold">
              Display Name
            </Label>
            <Input
              id="displayName"
              value={newName}
              onChange={(e) => setNewName(e.target.value)}
              placeholder="Enter your name"
              className="h-12 text-base"
            />
            <p className="text-xs text-muted-foreground">
              This name will be visible to other members in your trips.
            </p>
          </div>

          <div className="flex gap-3 pt-2">
            <Button 
              type="button" 
              variant="outline" 
              className="flex-1 h-11 text-base font-semibold" 
              onClick={() => onOpenChange(false)}
            >
              Cancel
            </Button>
            <Button 
              type="button" 
              className="flex-1 h-11 text-base font-semibold" 
              onClick={handleSaveName}
              disabled={savingName || !newName.trim()}
            >
              {savingName ? 'Saving...' : 'Save'}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
